### ISSUE TITLE
The fzf wrapper doesn't work: "too many arguments for function"

### ISSUE THREAD

**Issue by Bannerets** [voldikss/vim-floaterm#67]
I see it when I execute `FloatermNew fzf`:

```
Error detected while processing function floaterm#new:
line   16:
E118: Too many arguments for function: floaterm#wrapper#fzf#
E15: Invalid expression: WrapFunc(arg)
```

I guess it broke in commit 8d9ee69054f3c64e4fa22891497ca35efae16004

**Comment by voldikss** [comment]
Thanks, fixed
